name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - run: npm install pug-cli -g

    - run: dotnet build

    - uses: rvolo/xml-replace-action@v0.3
      with:
        filepath: "About/About.xml"
        xpath: "/ModMetaData/packageId/text()"
        replace: "caaz.typhon"

    - uses: rvolo/xml-replace-action@v0.3
      with:
        filepath: "About/About.xml"
        xpath: "/ModMetaData/name/text()"
        replace: "Typhon"

    - uses: actions/upload-artifact@v2
      with:
        name: Typhon
        path: |
          About
          Assemblies
          Defs
          Patches
          Textures
          Sounds
          News
          *.md
