name: Build

on:
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run buildpug production
        npm run buildsource
    - uses: actions/upload-artifact@v2
      with:
        name: Typhon
        path: |
          Languages
          About
          Assemblies
          Defs
          Patches
          Textures
          Sounds
          News
          *.md