name: Release

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/Build.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: Typhon
    - name: Set Environment Variables
      run: |
        echo "workshop_id=$(cat About/PublishedFileId.txt)" >> $GITHUB_ENV
        echo "mod_name=$(ls ..)" >> $GITHUB_ENV
    - name: Prepare for Distribution
      run: |
        mkdir ${{ env.mod_name }}
        mv `ls -I ${{ env.mod_name }}` ${{ env.mod_name }}
        7z a ${{ env.mod_name }}.zip ${{ env.mod_name }}
    - name: Create Github Release
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        release_name: "Release #${{ github.run_number }}"
        tag_name: release/${{ github.run_number }}
        asset_files: ${{env.mod_name}}.zip
